version: '3'
services:
  web:
    container_name: web
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./data:/data
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shifoumi
    
  php:
    container_name: php
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./data:/data
    networks:
      - shifoumi

  database:
      container_name: database
      volumes:
       - db-data:/var/lib/mysql
      image: 'mysql'
      environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      ports:
          - '3306'
      networks:
        - shifoumi
      restart: always

    
    


  phpmyadmin:
      container_name: pma
      image: phpmyadmin
      restart: always
      ports:
          - 8080:80
      environment:
          PMA_HOST: database
          UPLOAD_LIMIT: 300M
      networks:
        - shifoumi



networks:
  shifoumi:
    driver: bridge

volumes:
  db-data: {}