version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./data:/data
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shifoumi
    
  php:
    image: php:8-fpm
    volumes:
      - ./data:/data
    networks:
      - shifoumi



networks:
  shifoumi:
    driver: bridge